### ISSUE TITLE
Integration with failsafe plugin

### ISSUE THREAD

**Issue by jakob-o** [QualInsight/qualinsight-mojo-cobertura#34] opened 2017-03-11 14:56 UTC
Hi,
it took me some time to make the integration test coverage work with the failsafe plugin. The key was to set the <code>destionationDirectoryPath</code> correctly, e.g.
```
<execution>
    <id>instrument-it</id>
    <goals>
        <goal>instrument-it</goal>
    </goals>
    <phase>package</phase>
    <configuration>
        <destinationDirectoryPath>${project.build.directory}/test-classes</destinationDirectoryPath>
    </configuration>
</execution>
```

Maybe you want to add this to the documentation.

Regards

Jakob

**Comment by pawlakm** [comment] 2017-03-11 18:09
Hi, 

Thanks for your feedback. 

I'm wondering what's the real cause of your problem (or your context). Usually when using Maven, _system under test_ classes are compiled to ``classes`` (these are the classes you want to instrument) while test classes are compiled to ``test-classes``. The test classpath is built by failsafe using both directories (see [failsafe documentation](http://maven.apache.org/plugins-archives/maven-failsafe-plugin-2.11/examples/configuring-classpath.html)) you shouldn't have to instrument your test classes (unless you want to measure if your test classes are covered using tests...) Something sounds strange in your issue.

So here are some questions:

- why do you need to instrument your test classes ?
- did you check the [companion example project](https://github.com/QualInsight/qualinsight-mojo-cobertura-example) ? It is using surefire (see `ittests` module) and there is no special configuration involved.
- can you share a simple project to reproduce the problem ?

Kind regards,

Michel

P.S. did you try with version 2.0.0 ?

**Comment by jakob-o** [comment] 2017-03-12 20:42
Hey,

theoretically you are absolutely right. Unfortunately I have no proper explanation. However I was able to reproduce the issue with the 2.0.0-SNAPSHOT:
https://github.com/jakob-o/qualinsight-mojo-cobertura-test

I ran the projecti with
```
mvn -X clean verify
```

The "hack" I used does not work in the project (neither 1.1.0 nor 2.0.0-SNAPSHOT). Additionally you can observe that the `<sources>`-tag is not populated as mentioned in issue #33


Regards

Jakob

EDIT: I managed to reproduce the hack too, see branch 1.1.0-hack. A wild guess is that the instrumented classes are generated to the test classes directory and somehow are inserted in the classpath before the actual (non-instrumented) classes and therefore actually used.

**Comment by jakob-o** [comment] 2017-03-13 08:24
Jep, seems like my suspicion might be correct. This is the output with an explicit configured classes directory for the generated classes and additional classpath entry for failsafe:
```
[DEBUG] test classpath:  /home/jakob/source/java/qualinsight-mojo-cobertura-test/target/test-classes
/home/jakob/source/java/qualinsight-mojo-cobertura-test/target/qualinsight-mojo-cobertura-test-0.0.1-SNAPSHOT.jar
...
/home/jakob/source/java/qualinsight-mojo-cobertura-test/target/cobertura/it/instrumented-classes
```
The problem seems to be that the generated jar (with the non-instrumented classes) is inserted into the classpath before the instrumented classes directory. Whereas the test-classes directory is the first in the classpath.

**Comment by jakob-o** [comment] 2017-03-13 08:41
Btw. am I correct that 2.0.0 does not support `<destinationDirectoryPath>` anymore, or is this another issue?

**Comment by jakob-o** [comment] 2017-03-13 08:59
OK, I figured it out!

Setting the `<classesDirectory>` to `${project.build.directory}/classes` in the failsafe plugin is sufficient. However, be aware that this seems not to be respected in the latest version `2.19.1`! It works as expected / [documented](http://maven.apache.org/plugins-archives/maven-failsafe-plugin-2.11/integration-test-mojo.html#classesDirectory) with version `2.18.1`. This might be [bug in failsafe](https://issues.apache.org/jira/browse/SUREFIRE-1343). You can find a working setup in the [working setup branch](https://github.com/jakob-o/qualinsight-mojo-cobertura-test/blob/working-setup/pom.xml). You still might want to add this to the documentation. Sorry for the noise.

Regards

Jakob

PS: The sources issue still persists but I will continue with this in the other issue.

**Comment by pawlakm** [comment] 2017-03-13 20:51
ok thanks for reporting this. I'll update the documentation accordingly.

**Comment by pawlakm** [comment] 2017-03-13 22:54
Hi again, after having merged your PRs I cannot reproduce the problem anymore. I'm closing the issue.

**Closed as completed by pawlakm** 2017-03-13 22:54 UTC
Labels: bug, wontfix

**Comment by jakob-o** [comment] 2017-03-14 08:10
Hey,

would you mind me adding the failsafe documentation to the Wiki?

Regards

Jakob

**Comment by pawlakm** [comment] 2017-03-14 18:37
If you can write this part of the documentation it would be great.

Regards

Michel

**Comment by jakob-o** [comment] 2017-03-15 10:25
Hey,

could you please check if [this](https://github.com/QualInsight/qualinsight-mojo-cobertura/wiki/Gathering-IT-test-coverage-data-when-running-with-Maven-Failsafe-Plugin) suits your requirements?

Regards

Jakob

**Comment by pawlakm** [comment] 2017-03-15 21:24
Hi Jakob,

First all thank you for the documentation. I tried to reproduce the issue, and better understand it. I also documented the issue as a "[known limitation](https://github.com/QualInsight/qualinsight-mojo-cobertura/wiki/Known-limitations)".

What I will do is to remove the documentation page you wrote and keep the message on the "known limitations" page. I know that you put effort in writing this documentation, however I think that it will be clearer this way. I added a thank you message by the way.

Michel

**Comment by pawlakm** [comment] 2017-03-15 21:25
Adding a wont fix tag as the problem is related to Maven failsafe plugin.

**Comment by jakob-o** [comment] 2017-03-15 21:57
Hey,

first of all thank you for the thank you note. I don't mind whether it is a "How to use" or "Known limitations" page. Personally I prefer to have a snippet I can copy and paste to create a working setup but in the end it is of course up to you how you want to present this.

Thanks again for creating and maintaining this plugin!

Regards

Jakob
